### PR TITLE
Update to v2.1.0

### PR DESCRIPTION
**Pull request by danielpilla**
Addressing `name` being removed from the `licenses/assignments` API.

### CODE REVIEW

**Comment by danielpilla** [comment]
@withdave ok done.

**Review by withdave — CHANGES_REQUESTED** [review]
Not a new bug, but sheet `Users`, bottom left chart has a spelling error (Assinged)

**Review by withdave — APPROVED** [review]
Good to go, we can address spelling now or next time.

**Review by QlikMertzi — COMMENTED** [review]
good to go!

**Pull request merged**
